files:
  - source: /locales/en/layout.json
    translation: /locales/%locale%/layout.json
  - source: /locales/en/home.json
    translation: /locales/%locale%/home.json
  - source: /locales/en/branding.json
    translation: /locales/%locale%/branding.json
  - source: /locales/en/contact.json
    translation: /locales/%locale%/contact.json
  - source: /locales/en/discord.json
    translation: /locales/%locale%/discord.json
  - source: /locales/en/downloads.json
    translation: /locales/%locale%/downloads.json
  - source: /locales/en/error404.json
    translation: /locales/%locale%/error404.json
