version: '3.9'

services:
  fpwebsite:
    image: fpwebsite:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./static
        target: /var/www/html/static
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT}:80"
